# Generated by Django 3.0.6 on 2020-06-03 11:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('job', models.TextField()),
                ('skills', models.TextField()),
                ('skills_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('job_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='file',
            index=django.contrib.postgres.indexes.GinIndex(fields=['skills_vector', 'job_vector'], name='main_file_skills__e367ac_gin'),
        ),
        
        migrations.RunSQL(
        """
            CREATE TRIGGER skills_vector_update BEFORE INSERT OR UPDATE
            ON main_file FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger('skills_vector', 'pg_catalog.english', 'skills')
        """,
        ),

        migrations.RunSQL(
        """
            CREATE TRIGGER job_vector_update BEFORE INSERT OR UPDATE
            ON main_file FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger('job_vector', 'pg_catalog.english', 'job')
        """,
        ),
    ]
